drivers: battery/charger: Fix uninitialized/unset variables
The update to Clang 22 caught several bugs in these drivers, where
variables were not initialized at all or even not set ever.

../drivers/battery/charger/s2mf301_charger/s2mf301_pmeter.c:1071:36: error: variable 'value' is uninitialized when passed as a const pointer argument here [-Werror,-Wuninitialized-const-pointer]
 1071 |                 POWER_SUPPLY_LSI_PROP_PM_VCHGIN, value);
      |                                                  ^~~~~
../drivers/battery/charger/s2mf301_charger/s2mf301_pmeter.c:1082:33: error: variable 'value' is uninitialized when passed as a const pointer argument here [-Werror,-Wuninitialized-const-pointer]
 1082 |                 POWER_SUPPLY_LSI_PROP_ICHGIN, value);
      |                                               ^~~~~
2 errors generated.

../drivers/battery/charger/s2mu106_charger/s2mu106_charger.c:1596:36: error: variable 'value' is uninitialized when passed as a const pointer argument here [-Werror,-Wuninitialized-const-pointer]
 1596 |                                                 POWER_SUPPLY_PROP_AUTHENTIC, value);
      |                                                                              ^~~~~
1 error generated.

../drivers/battery/charger/sm5714_charger/sm5714_charger.c:1304:66: error: variable 'value' is uninitialized when passed as a const pointer argument here [-Werror,-Wuninitialized-const-pointer]
 1304 |                 psy_do_property("battery", set, POWER_SUPPLY_PROP_CHARGE_TYPE, value);
      |                                                                                ^~~~~
1 error generated.

Change-Id: If62d8d9dae765747a6893997413c43690736a386
Signed-off-by: Flopster101 <nahuelgomez329@gmail.com>
Signed-off-by: Majaahh <maja.blaszczak@proton.me>