drivers: soc: samsung/exynos-cpupm: Fix uninitialized variable warning
After the update to clang 22 (r584948), the following error appears:

../drivers/soc/samsung/exynos-cpupm.c:1710:50: error: variable 'name' is uninitialized when used here [-Werror,-Wuninitialized]
 1710 |                         pr_err("Failed to allocate idle_ip [ip=%s].", name);
      |                                                                       ^~~~
../drivers/soc/samsung/exynos-cpupm.c:1706:19: note: initialize the variable 'name' to silence this warning
 1706 |                 const char *name;
      |                                 ^
      |                                  = NULL
1 error generated.

Change-Id: I79208f64666e316973c8a0e64d249c17eee6f0b7
Signed-off-by: Flopster101 <nahuelgomez329@gmail.com>
Signed-off-by: Majaahh <maja.blaszczak@proton.me>