drivers: soc: devfreq/exynos-devfreq: Fix uninitialized variable warning
After the update to clang 22 (r584948), the following error appears:

../drivers/devfreq/exynos/exynos-devfreq.c:1975:48: error: variable 'buf' is uninitialized when used here [-Werror,-Wuninitialized]
 1975 |                         of_property_match_string(np, "clock-names", buf))
      |                                                                     ^~~
../drivers/devfreq/exynos/exynos-devfreq.c:1855:17: note: initialize the variable 'buf' to silence this warning
 1855 |         const char *buf;
      |                        ^
      |                         = NULL
1 error generated.

Change-Id: I245e9a61af2f669a7f9875b1761b2847f6e5f471
Signed-off-by: Flopster101 <nahuelgomez329@gmail.com>
Signed-off-by: Majaahh <maja.blaszczak@proton.me>