Revert "ARM64: configs: Disable KFENCE"
* This reverts commit d7b77460b4c8e2a3c2b1932b5fe8ae107883e064.
* Reason:
ERROR: files are incompatible: Runtime info and framework compatibility matrix are incompatible: No compatible kernel requirement found (kernel FCM version = 7).
For kernel requirements at matrix level 7, Kernel config errors:
    Missing config CONFIG_KFENCE

Change-Id: Id30694dd5b7ebc8f8c4a4e0f103643785e3d16b8
Signed-off-by: Majaahh <maja.blaszczak@proton.me>