drivers: gpu: {arm,drm}: Rename `in_range()` function
This conflicts with the now exposed Linux minmax.h macro for in_range(),
causing errors like this:

../drivers/gpu/arm/bv_r38p1/mali_kbase_dummy_job_wa.c:56:64: error: too many arguments provided to function-like macro invocation
   56 | static bool in_range(const u8 *base, const u8 *end, off_t off, size_t sz)
      |                                                                ^
../include/linux/minmax.h:298:9: note: macro 'in_range' defined here
  298 | #define in_range(val, start, len)                                       \
      |         ^
../drivers/gpu/arm/bv_r38p1/mali_kbase_dummy_job_wa.c:56:21: error: expected ';' after top level declarator
   56 | static bool in_range(const u8 *base, const u8 *end, off_t off, size_t sz)
      |                     ^
      |                     ;
../drivers/gpu/arm/bv_r38p1/mali_kbase_dummy_job_wa.c:318:31: error: too many arguments provided to function-like macro invocation
  318 |         if (!in_range(fw, fw_end, 0, sizeof(*header))) {
      |                                      ^
../include/linux/minmax.h:298:9: note: macro 'in_range' defined here
  298 | #define in_range(val, start, len)                                       \
      |         ^
../drivers/gpu/arm/bv_r38p1/mali_kbase_dummy_job_wa.c:337:49: error: too many arguments provided to function-like macro invocation
  337 |         if (!in_range(fw, fw_end, header->info_offset, sizeof(*v2_info))) {
      |                                                        ^
../include/linux/minmax.h:298:9: note: macro 'in_range' defined here
  298 | #define in_range(val, start, len)                                       \
      |         ^
../drivers/gpu/arm/bv_r38p1/mali_kbase_dummy_job_wa.c:363:42: error: too many arguments provided to function-like macro invocation
  363 |                 if (!in_range(fw, fw_end, blob_offset, sizeof(*blob))) {
      |                                                        ^
../include/linux/minmax.h:298:9: note: macro 'in_range' defined here
  298 | #define in_range(val, start, len)                                       \
      |         ^
../drivers/gpu/arm/bv_r38p1/mali_kbase_dummy_job_wa.c:370:51: error: too many arguments provided to function-like macro invocation
  370 |                 if (!in_range(fw, fw_end, blob->payload_offset, blob->size)) {
      |                                                                 ^
../include/linux/minmax.h:298:9: note: macro 'in_range' defined here
  298 | #define in_range(val, start, len)                                       \
      |         ^
6 errors generated.

Necessary after [1].

[1] aosp-mirror/kernel_common@6183c65

Change-Id: I9c8f7c5d7078fdca7ff260b2c5b4b3aa9a496260
Signed-off-by: Flopster101 <nahuelgomez329@gmail.com>
Signed-off-by: Majaahh <maja.blaszczak@proton.me>